sudo: required
language: php
dist: trusty

php:
  - 7.2

addons:
  chrome: stable

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry npm install
  - npm run prod
