language: php

php:
  - '7.2'

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run prod

script:
  - cp .env.travis .env
  - ls -al
  - pwd
  - if [[ "$DRIVER" = 'phpdbg' ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 5a4f5a1b-2cae-4ccf-858f-4dd14e12a4e0
